project:
  type: book
  output-dir: docs
  
  
execute:
  echo: true

book:
<<<<<<< HEAD
  title: "Finding What are the Important Factors for Camera Price With Random Forest and Linear Regression"
=======
  title: "5293 Final Project"
>>>>>>> b6c8899eb2c888d991917a0de1f7989cbbb7e2a2
  author:
    - Hanzhong Yang (hy2870)
  repo-url: https://github.com/Aspirine2212/5293-in-class-4-17.git
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true


